version: "3.8"

services:
  elasticsearch:
    container_name: elastic-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.1
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata:/usr/share/elasticsearch/data
    environment:
      - cluster.name=elastic-cluster
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - ek-net
    ports:
      - 9200:9200

  kibana:
    container_name: kibana-container
    image: docker.elastic.co/kibana/kibana:8.1.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-container:9200
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data
    networks:
      - ek-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  ek-net:
    driver: bridge

volumes:
  certs:
    driver: local
  esdata:
    driver: local
  kibanadata:
    driver: local